services:
  nestjs:
    build:
      dockerfile: Dockerfile
      context: ./backend
      target: dev
    volumes:
      - ./backend:/usr/src/app/
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - postgre
  postgre:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data

