services:
  nestjs:
    build:
      dockerfile: backend/Dockerfile
      context: .
      target: dev
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 3000:3000
