services:
  nestjs:
    build:
      dockerfile: Dockerfile
      context: ./backend
      target: dev
    volumes:
      - ./backend:/usr/src/app/
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 3000:3000
